# version: "3.8"

# networks:
#   app-tier:
#     driver: bridge

# services:
#   mysqldb:
#     image: mysql:5.7
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - MYSQL_ALLOW_EMPTY_PASSWORD=true
#       - MYSQL_DATABASE=$MYSQLDB_DATABASE
#       - MYSQL_ROOT_HOST='%'
#       - DB_HOST=mysql
#       - DB_USER=$MYSQLDB_USER
#       - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - DB_NAME=$MYSQLDB_DATABASE
#       - DB_PORT=$MYSQLDB_DOCKER_PORT
#     ports:
#       - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#     networks:
#       - app-tier 
#     volumes:
#       - db:/var/lib/mysql
#   app:
#     depends_on:
#       - mysqldb
#     build: .
#     restart: unless-stopped
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     networks:
#       - app-tier 
#     stdin_open: true
#     tty: true
# volumes: 
#   db:







version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env 
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
      - "app/npde_modules"
    depends_on:
      - mysql_server


  mysql_server:
    image: mysql:8.0 
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD